# Erros acontecem e nem sempre s√£o inesperados. O Python utiliza de exce√ß√µes para sinalizar que ocorreram erros durante a execu√ß√£o de um c√≥digo e que nem sempre s√£o fatais.
# Podemos escrever testes que verificam que um erro deve ocorrer a partir de uma determinada entrada.
# üìù Um exemplo pode ser visto abaixo:

# codigo.py

# ...

def divide(a_number, other_number):
    "Retorna a divis√£o de a_number por other_number"
    return a_number / other_number

# test_codigo.py
import pytest
from codigo import is_odd, divide

# ...

def test_divide_when_other_number_is_zero_raises_an_exception():
    with pytest.raises(ZeroDivisionError, match="division by zero"):
        divide(2, 0)